using System.Collections.Generic;
using MBW.Generators.NonTryMethods.Tests.Helpers;
using MBW.Generators.Tests.Common;
using Microsoft.CodeAnalysis;
using Xunit;

namespace MBW.Generators.NonTryMethods.Tests;

public class Nullability_ValueTypes
{
    [Fact]
    public void Async_Verbatim_PreservesNullableT()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            TestsHelper.RunHelper("""
                                  using System.Threading.Tasks;
                                  using MBW.Generators.NonTryMethods.Attributes;

                                  [GenerateNonTryMethod]
                                  [GenerateNonTryOptions]
                                  public partial class TestClass
                                  {
                                      public Task<(bool ok, int? value)> TryMethodAsync()
                                          => Task.FromResult((true, (int?)42));
                                  }
                                  """);
        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;
                           using System.Threading.Tasks;

                           partial class TestClass
                           {
                               public async Task<int?> MethodAsync()
                               {
                                   var t = await TryMethodAsync();
                                   if (t.Item1)
                                   {
                                       return t.Item2;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }

    [Fact]
    public void Async_TrueMeansNotNull_UnwrapsNullable()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            TestsHelper.RunHelper("""
                                  using System.Threading.Tasks;
                                  using MBW.Generators.NonTryMethods.Attributes;

                                  [GenerateNonTryMethod]
                                  [GenerateNonTryOptions(returnGenerationStrategy: ReturnGenerationStrategy.TrueMeansNotNull)]
                                  public partial class TestClass
                                  {
                                      public Task<(bool ok, int? value)> TryMethodAsync()
                                          => Task.FromResult((true, (int?)42));
                                  }
                                  """);
        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;
                           using System.Threading.Tasks;

                           partial class TestClass
                           {
                               public async Task<int> MethodAsync()
                               {
                                   var t = await TryMethodAsync();
                                   if (t.Item1)
                                   {
                                       return t.Item2;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }

    [Fact]
    public void Sync_Verbatim_PreservesNullableT()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            TestsHelper.RunHelper("""
                                  using MBW.Generators.NonTryMethods.Attributes;

                                  [GenerateNonTryMethod]
                                  [GenerateNonTryOptions]
                                  public partial class TestClass
                                  {
                                      public bool TryMethod(out int? value)
                                      {
                                          value = 1;
                                          return true;
                                      }
                                  }
                                  """);
        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;

                           partial class TestClass
                           {
                               public int? Method()
                               {
                                   if (TryMethod(out var value))
                                   {
                                       return value;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }

    [Fact]
    public void Sync_TrueMeansNotNull_UnwrapsNullable()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            TestsHelper.RunHelper("""
                                  using MBW.Generators.NonTryMethods.Attributes;

                                  [GenerateNonTryMethod]
                                  [GenerateNonTryOptions(returnGenerationStrategy: ReturnGenerationStrategy.TrueMeansNotNull)]
                                  public partial class TestClass
                                  {
                                      public bool TryMethod(out int? value)
                                      {
                                          value = 1;
                                          return true;
                                      }
                                  }
                                  """);
        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;

                           partial class TestClass
                           {
                               public int Method()
                               {
                                   if (TryMethod(out var value))
                                   {
                                       return value;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }
}