using System.Collections.Generic;
using MBW.Generators.NonTryMethods.Tests.Helpers;
using MBW.Generators.Tests.Common;
using Microsoft.CodeAnalysis;
using Xunit;

namespace MBW.Generators.NonTryMethods.Tests;

public class Patterns
{
    [Fact]
    public void DefaultRegex_RemovesTryPrefix()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            TestsHelper.RunHelper("""
                                  using System.Threading.Tasks;
                                  using MBW.Generators.NonTryMethods.Generator.Attributes;

                                  [GenerateNonTryMethod] // default ^[Tt]ry(.*)
                                  [GenerateNonTryOptions]
                                  public partial class TestClass
                                  {
                                      public Task<(bool ok, string? value)> TryMethodAsync()
                                          => Task.FromResult((true, "x"));
                                  }
                                  """);
        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;
                           using System.Threading.Tasks;

                           partial class TestClass
                           {
                               public async Task<string?> MethodAsync()
                               {
                                   var tmp = await TryMethodAsync();
                                   if (tmp.Item1)
                                   {
                                       return tmp.Item2;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }

    [Fact]
    public void MultiplePatterns_SameSignature_Dedup()
    {
        (string? _, IReadOnlyList<Diagnostic> diags) =
            TestsHelper.RunHelper("""
                                  using MBW.Generators.NonTryMethods.Generator.Attributes;
                                  using System.Threading.Tasks;

                                  [GenerateNonTryMethod(methodNamePattern: "^[Tt]ry(.*)$")]
                                  [GenerateNonTryMethod(methodNamePattern: "^Try(.*)$")]
                                  [GenerateNonTryOptions]
                                  public partial class TestClass
                                  {
                                      public Task<(bool ok, string? value)> TryMethodAsync()
                                          => Task.FromResult((true, "x"));
                                  }
                                  """);
        Assert.Collection(diags,
            d => Assert.Equal(Diagnostics.MultiplePatternsMatchMethod.Id, d.Id));
    }
}