using System.Collections.Generic;
using MBW.Generators.NonTryMethods.Tests.Helpers;
using MBW.Generators.Tests.Common;
using Microsoft.CodeAnalysis;
using Xunit;

namespace MBW.Generators.NonTryMethods.Tests;

public class Functionality
{
    [Fact]
    public void SyncBoolOut_Defaults()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            TestsHelper.RunHelper("""
                                  [GenerateNonTryMethod]
                                  [GenerateNonTryOptions]
                                  public partial class TestClass
                                  {
                                      public bool TryLoad(int a, int b, out int value)
                                      {
                                          value = a + b;
                                          return a >= 0 && b >= 0;
                                      }
                                  }
                                  """);

        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;

                           partial class TestClass
                           {
                               public int Load(int a, int b)
                               {
                                   if (TryLoad(a, b, out var value))
                                   {
                                       return value;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }

    [Fact]
    public void SyncBoolOut_CustomException()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            TestsHelper.RunHelper("""
                                  using System;
                                  
                                  public class MyEx : Exception {}

                                  [GenerateNonTryMethod(typeof(MyEx))]
                                  [GenerateNonTryOptions]
                                  public partial class TestClass
                                  {
                                      public bool TryLoad(int a, int b, out int value)
                                      {
                                          value = a + b;
                                          return false;
                                      }
                                  }
                                  """);

        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;

                           partial class TestClass
                           {
                               public int Load(int a, int b)
                               {
                                   if (TryLoad(a, b, out var value))
                                   {
                                       return value;
                                   }

                                   throw new MyEx();
                               }
                           }
                           """, output);
    }

    [Fact]
    public void TaskTuple_Verbatim()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            TestsHelper.RunHelper("""
                                  using System.Threading.Tasks;
                                  
                                  [GenerateNonTryMethod]
                                  [GenerateNonTryOptions]
                                  public partial class TestClass
                                  {
                                      public Task<(bool ok, string? value)> TryLoadAsync(int id)
                                          => Task.FromResult((id > 0, id > 0 ? $"#{id}" : null));
                                  }
                                  """);

        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;
                           using System.Threading.Tasks;

                           partial class TestClass
                           {
                               public async Task<string?> LoadAsync(int id)
                               {
                                   var tmp = await TryLoadAsync(id);
                                   if (tmp.Item1)
                                   {
                                       return tmp.Item2;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }

    [Fact]
    public void ValueTaskTuple_Verbatim()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            TestsHelper.RunHelper("""
                                  using System.Threading.Tasks;
                                  
                                  [GenerateNonTryMethod]
                                  [GenerateNonTryOptions]
                                  public partial class TestClass
                                  {
                                      public ValueTask<(bool ok, int? value)> TryLoadAsync(int id)
                                          => new ValueTask<(bool,int?)>((id > 0, id > 0 ? id : (int?)null));
                                  }
                                  """);

        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;
                           using System.Threading.Tasks;

                           partial class TestClass
                           {
                               public async ValueTask<int?> LoadAsync(int id)
                               {
                                   var tmp = await TryLoadAsync(id);
                                   if (tmp.Item1)
                                   {
                                       return tmp.Item2;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }

    [Fact]
    public void TaskTuple_TrueMeansNotNull_ReferencePayload()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            TestsHelper.RunHelper("""
                                  using System.Threading.Tasks;
                                  
                                  [GenerateNonTryMethod]
                                  [GenerateNonTryOptions(returnGenerationStrategy: ReturnGenerationStrategy.TrueMeansNotNull)]
                                  public partial class TestClass
                                  {
                                      public Task<(bool ok, string? value)> TryLoadAsync(int id)
                                          => Task.FromResult((id > 0, id > 0 ? $"#{id}" : null));
                                  }
                                  """);

        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;
                           using System.Threading.Tasks;

                           partial class TestClass
                           {
                               public async Task<string> LoadAsync(int id)
                               {
                                   var tmp = await TryLoadAsync(id);
                                   if (tmp.Item1)
                                   {
                                       return tmp.Item2;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }
}