using System.Collections.Generic;
using System.Threading.Tasks;
using MBW.Generators.NonTryMethods.Tests.Helpers;
using MBW.Generators.Tests.Common;
using Microsoft.CodeAnalysis;
using Xunit;

namespace MBW.Generators.NonTryMethods.Tests;

public class StrategyMatrixClasses
{
    [Fact]
    public async Task Auto_PartialInPlace()
    {
        // Should emit: error CS0260: Missing partial modifier on declaration of type 'TestClass'; another partial declaration of this type exists]
        (string? output, IReadOnlyList<Diagnostic> diags) =
            await TestsHelper.RunHelperAsync("""
                                             [GenerateNonTryMethod]
                                             [GenerateNonTryOptions(methodsGenerationStrategy: MethodsGenerationStrategy.Auto)]
                                             public class TestClass
                                             {
                                                 public bool TryMethod(out int v) { v = 1; return true; }
                                             }
                                             """, ["CS0260"]);
        
        Assert.Collection(diags, d => Assert.Equal("CS0260", d.Id));
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;

                           partial class TestClass
                           {
                               public int Method()
                               {
                                   if (TryMethod(out var v))
                                   {
                                       return v;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }

    [Fact]
    public async Task Partial_ExplicitInPlace()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            await TestsHelper.RunHelperAsync("""
                                             [GenerateNonTryMethod]
                                             [GenerateNonTryOptions(methodsGenerationStrategy: MethodsGenerationStrategy.PartialType)]
                                             public partial class TestClass
                                             {
                                                 public bool TryMethod(out int v) { v = 1; return true; }
                                             }
                                             """);
        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;

                           partial class TestClass
                           {
                               public int Method()
                               {
                                   if (TryMethod(out var v))
                                   {
                                       return v;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }

    [Fact]
    public async Task Extensions_InstanceReceiver()
    {
        (string? output, IReadOnlyList<Diagnostic> diags) =
            await TestsHelper.RunHelperAsync("""
                                             [GenerateNonTryMethod]
                                             [GenerateNonTryOptions(methodsGenerationStrategy: MethodsGenerationStrategy.Extensions)]
                                             public class TestClass
                                             {
                                                 public bool TryMethod(out int v) { v = 2; return true; }
                                             }
                                             """);
        Assert.Empty(diags);
        SyntaxHelper.Equal("""
                           // <auto-generated/>
                           #nullable enable
                           using System;

                           public static class TestClass_NonTryExtensions
                           {
                               public static int Method(this TestClass self)
                               {
                                   if (self.TryMethod(out var v))
                                   {
                                       return v;
                                   }

                                   throw new InvalidOperationException();
                               }
                           }
                           """, output);
    }

    [Fact]
    public async Task Extensions_StaticInput_ReportsCannotGenerateExtensionForStatic()
    {
        (string? _, IReadOnlyList<Diagnostic> diags) =
            await TestsHelper.RunHelperAsync("""

                                             [GenerateNonTryMethod]
                                             [GenerateNonTryOptions(methodsGenerationStrategy: MethodsGenerationStrategy.Extensions)]
                                             public class TestClass
                                             {
                                                 public static bool TryMethod(out int v) { v = 0; return false; }
                                             }
                                             """);
        Assert.Collection(diags,
            d => Assert.Equal(Diagnostics.UnableToGenerateExtensionMethodForStaticMethod.Id, d.Id));
    }
}